name: Upload Zipped Directory to Release

on:
  release:
    types: [created]

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the folder correctly
        run: |
          cd folder
          zip -r ../zipped_dir.zip *

      - name: Upload Zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: zipped_dir.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}