name: build zip
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: create zip
        run: |
          zip -r poisoned-prism.zip . -x .git. .github. .gitignore README.md
      
      - name: capture zip
        uses: actions/upload-artifact@v7.0.1
        with:
          path: |
            poisoned-prism.zip
          archive: false